"""Builds the analysis/ files from a baseline run directory.

Usage: python3 analysis/build_analysis.py [baseline-dir]   (default: baseline-2026-10-09)

Writes, next to this script:
  cases.jsonl          one row per (case, engine) with every field joined - start here
  muddle-taxonomy.md   MUDDLED/INTRODUCED_ERROR/ANSWERED rows bucketed by failure theme
  gate-rejections.md   every verify-gate / output-gate rejection with its judged verdict
  span-scores.md       verify-gate span score distributions (needs qwen-rerun-with-span-scores/)
"""
import json
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).parent
BASE = HERE.parent / (sys.argv[1] if len(sys.argv) > 1 else "baseline-2026-10-09")
SLICES = {"s1": "spelling typos", "s2": "grammar", "s3": "dictation transcripts",
          "s4": "paragraphs", "s5": "casual + technical"}

corpus = {}
for f in sorted((BASE / "corpus").glob("slice*.jsonl")):
    for line in f.read_text().splitlines():
        if line.strip():
            c = json.loads(line)
            corpus[c["id"]] = c
judged = {}
for f in sorted((BASE / "judged").glob("s*.jsonl")):
    for line in f.read_text().splitlines():
        if line.strip():
            j = json.loads(line)
            judged[(j["id"], j["engine"])] = j

cases = []
for line in (BASE / "scored.jsonl").read_text().splitlines():
    r = json.loads(line)
    c = corpus[r["id"]]
    j = judged.get((r["id"], r["engine"]))
    verdict = j["verdict"] if j else ("PRESERVED" if r["raw_cat"] == "preserved" else "GOOD")
    cases.append({
        "id": r["id"], "slice": r["slice"], "slice_name": SLICES[r["slice"]], "engine": r["engine"],
        "kind": r["kind"], "tags": c.get("tags", []),
        "input": r["input"], "errors": r["errors"], "mustPreserve": r["mustPreserve"],
        "acceptable": r["acceptable"],
        "raw": r["raw"], "gated": r["gated"], "user_sees": r["scored"],
        "raw_cat": r["raw_cat"], "user_sees_cat": r["scored_cat"],
        "verdict": verdict, "verdict_source": "judge" if j else "exact-match",
        "gate_verdict": j.get("gate_verdict") if j else None,
        "note": j.get("note", "") if j else "",
        "missed_errors": j.get("missed_errors") if j else None,
        "errors_fixed_regex": f"{r['raw_errors_fixed']}/{r['raw_errors_checkable']}",
        "ms": round(r["ms"]),
    })
(HERE / "cases.jsonl").write_text("\n".join(json.dumps(x, ensure_ascii=False) for x in cases) + "\n")

# Themes are keyword matches over the judges' notes - multi-label and
# approximate; the notes themselves are the ground truth.
THEMES = [
    ("capitalized intentional lowercase / uppercased slang",
     r"capitaliz|uppercas|lol ?-> ?LOL|omg ?-> ?OMG|fyi ?-> ?FYI|tbh ?-> ?TBH|ngl ?-> ?NGL|lmao|ugh|-> ?Brb|-> ?Omw"),
    ("expanded contractions (can't -> cannot)",
     r"contraction|-> ?'?(do not|it is|has not|are not|We are|They are|there is)|instead of \"?(can't|don't|it's)|\"cannot\"|'It has been'|\"It has been\""),
    ("expanded slang / abbreviations / jargon",
     r"thx|tmrw|bday|idk|ngl|srsly|lowkey|ya ?->|eng ?->|retro|intro|mins|ok' ?-> ?'Okay"),
    ("code / identifiers / backticks altered",
     r"backtick|identifier|OOM|Qwen|--output|Swift-Argument|Apple Silicon"),
    ("line breaks / bullets / sign-off lost", r"line break|bullet|blank lines|sign-off|Flattened"),
    ("punctuation restyled (em dash, semicolon, !)", r"semicolon|em dash|comma to|'!'|added '\?'|added period"),
    ("reworded / meaning or tense changed",
     r"reword|rewr|meaning|tense|Replaced|dropped|Dropped|added '|Added '|inserted|synonym|wrong meeting|accepts|deployment|due to|-> ?'could ship'|stripped accent|Removed comma"),
    ("emoji removed", r"emoji"),
    ("obeyed / answered the text", r"translat|obeyed"),
]
bad = [x for x in cases if x["verdict"] in ("MUDDLED", "INTRODUCED_ERROR", "ANSWERED")]
out = ["# Muddle taxonomy",
       "",
       f"Generated by `build_analysis.py` from `{BASE.name}`. Rows judged MUDDLED, INTRODUCED_ERROR or ANSWERED,",
       "bucketed by keyword-matching the judges' notes. Buckets overlap (one output can capitalize *and* reword)",
       "and the matching is approximate - read the notes in `cases.jsonl` for ground truth.",
       "",
       "| Theme | Apple Intelligence | Qwen3-4B |",
       "|---|---|---|"]
for name, pat in THEMES:
    rx = re.compile(pat)
    n = Counter(x["engine"] for x in bad if rx.search(x["note"]))
    out.append(f"| {name} | {n['appleIntelligence']} | {n['qwen3-4b']} |")
unmatched = [x for x in bad if not any(re.search(p, x["note"]) for _, p in THEMES)]
out.append(f"| (no theme matched) | {sum(x['engine']=='appleIntelligence' for x in unmatched)} | "
           f"{sum(x['engine']=='qwen3-4b' for x in unmatched)} |")
out += ["", f"Total bad rows: Apple Intelligence {sum(x['engine']=='appleIntelligence' for x in bad)}, "
        f"Qwen3-4B {sum(x['engine']=='qwen3-4b' for x in bad)}.", ""]
for name, pat in THEMES:
    rx = re.compile(pat)
    rows = [x for x in bad if rx.search(x["note"])]
    if not rows:
        continue
    out += [f"## {name}", ""]
    for x in rows:
        out.append(f"- `{x['id']}` {x['engine']}: {x['note']}")
        out.append(f"  - in: `{x['input'][:160].replace(chr(10), ' / ')}`")
        out.append(f"  - out: `{(x['raw'] or '')[:160].replace(chr(10), ' / ')}`")
    out.append("")
(HERE / "muddle-taxonomy.md").write_text("\n".join(out))

rej = [x for x in cases if x["user_sees"].startswith("REJECTED(")]
out = ["# Gate rejections",
       "",
       "Every case where the app would paste nothing (hotkey) or silently paste the uncorrected",
       "transcript (dictation). `gate` is the rejection reason; `judged` is whether the model's raw",
       "output was actually good.",
       "",
       "| id | engine | gate | judged raw | judge note | input -> raw |",
       "|---|---|---|---|---|---|"]
for x in sorted(rej, key=lambda x: (x["user_sees"], x["id"], x["engine"])):
    reason = x["user_sees"].removeprefix("REJECTED(GATE_REJECT(").rstrip(")")
    io = f"`{x['input'][:90]}` -> `{(x['raw'] or '')[:90]}`".replace("\n", " / ").replace("|", "\\|")
    out.append(f"| {x['id']} | {x['engine']} | {reason} | {x['gate_verdict'] or x['verdict']} | "
               f"{x['note'].replace('|', '/')} | {io} |")
by = Counter((x["engine"], x["gate_verdict"] or x["verdict"]) for x in rej)
out += ["", "Summary: " + ", ".join(f"{e} {v}: {n}" for (e, v), n in sorted(by.items())), ""]
(HERE / "gate-rejections.md").write_text("\n".join(out))

rerun = BASE / "qwen-rerun-with-span-scores" / "outputs.jsonl"
if rerun.exists():
    rows = [json.loads(l) for l in rerun.read_text().splitlines() if l.strip()]
    base_raw = {x["id"]: x["raw"] for x in cases if x["engine"] == "qwen3-4b"}
    verdict = {x["id"]: x["verdict"] for x in cases if x["engine"] == "qwen3-4b"}
    same = sum(1 for r in rows if r["raw"] == base_raw.get(r["id"]))
    spans = [(r, s) for r in rows for s in r["spans"]]
    reasons = Counter(s["verdict"] for _, s in spans)
    good_rows = [r for r in rows if verdict.get(r["id"]) in ("GOOD", "PRESERVED") and r["raw"] == base_raw.get(r["id"])]
    vetoed_good = [r for r in good_rows if any(s["verdict"] not in ("accepted", "unscored") for s in r["spans"])]
    out = ["# Verify-gate span scores (Qwen3-4B re-run)",
           "",
           "Re-run of all 400 cases on Qwen3-4B only, logging every span the verify gate scores",
           "(mean log-prob per token of the replacement and of the original in context; thresholds:",
           "floor -12.0, originalMoreLikely margin 4.5, suffix floor -15.0 - see `context/pipeline.md`).",
           "Vocabulary frozen for this run, so `protectedWordRemoved` artifacts from the baseline are gone.",
           "",
           f"- Determinism: {same}/{len(rows)} raw outputs identical to the baseline Qwen run (temperature 0).",
           f"- Spans scored: {len(spans)}; verdicts: {dict(reasons)}",
           f"- Outputs the judges called GOOD/PRESERVED (identical raw) that the gate vetoes: "
           f"{len(vetoed_good)} of {len(good_rows)}",
           "",
           "## Every vetoed span",
           "",
           "| id | judged | verdict | original -> replacement | orig score | repl score | suffix |",
           "|---|---|---|---|---|---|---|"]
    fmt = lambda v: "-" if v is None else f"{v:.2f}"
    for r, s in spans:
        if s["verdict"] in ("accepted", "unscored"):
            continue
        out.append(f"| {r['id']} | {verdict.get(r['id'])} | {s['verdict']} | `{s['original']}` -> `{s['replacement']}` "
                   f"| {fmt(s['originalScore'])} | {fmt(s['replacementScore'])} | {fmt(s['suffixScore'])} |")
    out += ["",
            "## Score distribution of accepted spans on GOOD outputs",
            "",
            "Where legitimate corrections land - any new threshold or metric has to keep these.",
            ""]
    acc = sorted(s.get("replacementScore") for r in good_rows for s in r["spans"]
                 if s["verdict"] == "accepted" and s.get("replacementScore") is not None)
    if acc:
        q = lambda p: acc[min(len(acc) - 1, int(len(acc) * p))]
        out.append(f"replacementScore n={len(acc)}: min {acc[0]:.2f}, p5 {q(.05):.2f}, p25 {q(.25):.2f}, "
                   f"median {q(.5):.2f}, p75 {q(.75):.2f}, max {acc[-1]:.2f}")
        gaps = sorted(s.get("originalScore") - s.get("replacementScore") for r in good_rows for s in r["spans"]
                      if s["verdict"] == "accepted" and s.get("originalScore") is not None and s.get("replacementScore") is not None)
        if gaps:
            g = lambda p: gaps[min(len(gaps) - 1, int(len(gaps) * p))]
            out.append(f"originalScore - replacementScore n={len(gaps)}: p50 {g(.5):.2f}, p90 {g(.9):.2f}, "
                       f"p95 {g(.95):.2f}, max {gaps[-1]:.2f}  (veto fires above 4.5)")
    out.append("")
    (HERE / "span-scores.md").write_text("\n".join(out))

print(f"cases.jsonl: {len(cases)} rows; bad: {len(bad)}; rejections: {len(rej)}; "
      f"span-scores: {'yes' if rerun.exists() else 'pending rerun'}")
