import json
import sys

P = "missing punctuation/capitalization"

FIX = [
    ("hey can you send me the slides from yesterdays meeting i want to right a summary for the team",
     ["Hey, can you send me the slides from yesterday's meeting? I want to write a summary for the team.",
      "Hey, can you send me the slides from yesterday's meeting? I want to write a summary for the team!"],
     [P, "yesterdays -> yesterday's", "right -> write"]),
    ("i dont know weather we should push the release to friday or just ship it tomorrow what do you think",
     ["I don't know whether we should push the release to Friday or just ship it tomorrow. What do you think?",
      "I don't know whether we should push the release to Friday or just ship it tomorrow - what do you think?"],
     [P, "dont -> don't", "weather -> whether", "friday -> Friday"]),
    ("thanks for the update ill take a look at it after lunch and get back to you",
     ["Thanks for the update. I'll take a look at it after lunch and get back to you.",
      "Thanks for the update! I'll take a look at it after lunch and get back to you."],
     [P, "ill -> I'll"]),
    ("note to self pick up dry cleaning before six and call the dentist about moving my appointment",
     ["Note to self: pick up dry cleaning before six and call the dentist about moving my appointment.",
      "Note to self: Pick up dry cleaning before six and call the dentist about moving my appointment.",
      "Note to self - pick up dry cleaning before six and call the dentist about moving my appointment."],
     [P]),
    ("were running a little late so start the call without us well join in about ten minutes",
     ["We're running a little late, so start the call without us. We'll join in about ten minutes.",
      "We're running a little late, so start the call without us - we'll join in about ten minutes."],
     [P, "were -> We're", "well -> we'll"]),
    ("the new build is way faster then the old one but its still crashing on launch for some users",
     ["The new build is way faster than the old one, but it's still crashing on launch for some users.",
      "The new build is way faster than the old one but it's still crashing on launch for some users."],
     [P, "then -> than", "its -> it's"]),
    ("everyone accept sarah has signed off on the design so we just need her approval before we merge",
     ["Everyone except Sarah has signed off on the design, so we just need her approval before we merge.",
      "Everyone except Sarah has signed off on the design. So we just need her approval before we merge."],
     [P, "accept -> except", "sarah -> Sarah"]),
    ("can you let me no when the invoice goes out i need to tell finance",
     ["Can you let me know when the invoice goes out? I need to tell finance.",
      "Can you let me know when the invoice goes out? I need to tell Finance."],
     [P, "no -> know"]),
    ("i think we should meet at the the coffee shop on main street instead of the office",
     ["I think we should meet at the coffee shop on Main Street instead of the office."],
     [P, "the the -> the", "main street -> Main Street"]),
    ("their going to need the final numbers by end of day so please prioritize that over the deck",
     ["They're going to need the final numbers by end of day, so please prioritize that over the deck.",
      "They're going to need the final numbers by end of day. Please prioritize that over the deck."],
     [P, "their -> They're"]),
    ("i should of checked the logs before restarting the server sorry about that",
     ["I should have checked the logs before restarting the server. Sorry about that.",
      "I should've checked the logs before restarting the server. Sorry about that.",
      "I should have checked the logs before restarting the server - sorry about that."],
     [P, "should of -> should have"]),
    ("hi tom just wanted to follow up on the contract did you get a chance to review it",
     ["Hi Tom, just wanted to follow up on the contract. Did you get a chance to review it?",
      "Hi Tom, I just wanted to follow up on the contract. Did you get a chance to review it?",
      "Hi Tom - just wanted to follow up on the contract. Did you get a chance to review it?"],
     [P, "tom -> Tom"]),
    ("the meeting is at too thirty in the big conference room bring your laptop",
     ["The meeting is at two thirty in the big conference room. Bring your laptop.",
      "The meeting is at 2:30 in the big conference room. Bring your laptop.",
      "The meeting is at two-thirty in the big conference room. Bring your laptop."],
     [P, "too -> two"]),
    ("lets grab lunch next week im free tuesday and thursday",
     ["Let's grab lunch next week. I'm free Tuesday and Thursday.",
      "Let's grab lunch next week - I'm free Tuesday and Thursday."],
     [P, "lets -> Let's", "im -> I'm", "tuesday -> Tuesday", "thursday -> Thursday"]),
    ("i cant find the file you mentioned is it in the shared drive or did you email it",
     ["I can't find the file you mentioned. Is it in the shared drive, or did you email it?",
      "I can't find the file you mentioned. Is it in the shared drive or did you email it?"],
     [P, "cant -> can't"]),
    ("the dog needs to go to the vet on saturday dont forget to bring his records",
     ["The dog needs to go to the vet on Saturday. Don't forget to bring his records.",
      "The dog needs to go to the vet on Saturday - don't forget to bring his records."],
     [P, "saturday -> Saturday", "dont -> don't"]),
    ("who's turn is it to write the release notes this week",
     ["Whose turn is it to write the release notes this week?"],
     [P, "who's -> Whose"]),
    ("please except my apologies for the delay i was out sick most of last week",
     ["Please accept my apologies for the delay. I was out sick most of last week.",
      "Please accept my apologies for the delay; I was out sick most of last week."],
     [P, "except -> accept"]),
    ("we need to by more coffee for the office were completely out",
     ["We need to buy more coffee for the office. We're completely out.",
      "We need to buy more coffee for the office - we're completely out."],
     [P, "by -> buy", "were -> we're"]),
    ("i'll be their in five minutes just parking the car",
     ["I'll be there in five minutes, just parking the car.",
      "I'll be there in five minutes. Just parking the car.",
      "I'll be there in five minutes - just parking the car."],
     [P, "their -> there"]),
    ("can you review my pull request when you get a chance its the one that fixes the login bug",
     ["Can you review my pull request when you get a chance? It's the one that fixes the login bug."],
     [P, "its -> It's"]),
    ("the client said they want to loose the blue header and go with something more neutral",
     ["The client said they want to lose the blue header and go with something more neutral."],
     [P, "loose -> lose"]),
    ("reminder to email the landlord about the leak under the kitchen sink its getting worse",
     ["Reminder to email the landlord about the leak under the kitchen sink. It's getting worse.",
      "Reminder: email the landlord about the leak under the kitchen sink. It's getting worse.",
      "Reminder to email the landlord about the leak under the kitchen sink - it's getting worse."],
     [P, "its -> It's"]),
    ("i herd back from the recruiter and they want to schedule a second interview",
     ["I heard back from the recruiter, and they want to schedule a second interview.",
      "I heard back from the recruiter and they want to schedule a second interview."],
     [P, "herd -> heard"]),
    ("does anyone know where the extra chargers went i left too in the drawer yesterday",
     ["Does anyone know where the extra chargers went? I left two in the drawer yesterday."],
     [P, "too -> two"]),
    ("its been a long week so im going to log off early see everyone monday",
     ["It's been a long week, so I'm going to log off early. See everyone Monday.",
      "It's been a long week, so I'm going to log off early. See everyone Monday!"],
     [P, "its -> It's", "im -> I'm", "monday -> Monday"]),
    ("the report is due on the fifteenth but i think we can get it done buy the twelfth",
     ["The report is due on the fifteenth, but I think we can get it done by the twelfth.",
      "The report is due on the fifteenth but I think we can get it done by the twelfth."],
     [P, "buy -> by"]),
    ("could you please pass this along to the design team i want there feedback before friday",
     ["Could you please pass this along to the design team? I want their feedback before Friday."],
     [P, "there -> their", "friday -> Friday"]),
    ("we're going to need a bigger budget for q three if we want to hire two more engineers",
     ["We're going to need a bigger budget for Q3 if we want to hire two more engineers.",
      "We're going to need a bigger budget for Q three if we want to hire two more engineers."],
     [P, "q three -> Q3"]),
    ("i was going to call you but than i realized you were probably in the meeting",
     ["I was going to call you, but then I realized you were probably in the meeting.",
      "I was going to call you but then I realized you were probably in the meeting."],
     [P, "than -> then"]),
    ("quick question did the shipment arrive or is it still stuck in customs",
     ["Quick question: did the shipment arrive, or is it still stuck in customs?",
      "Quick question - did the shipment arrive or is it still stuck in customs?",
      "Quick question: Did the shipment arrive or is it still stuck in customs?"],
     [P]),
    ("make sure you lock the back door when you leave the alarm code is the same as before",
     ["Make sure you lock the back door when you leave. The alarm code is the same as before."],
     [P]),
    ("the effect of the new pricing hasnt shown up in the numbers yet give it another week",
     ["The effect of the new pricing hasn't shown up in the numbers yet. Give it another week.",
      "The effect of the new pricing hasn't shown up in the numbers yet - give it another week."],
     [P, "hasnt -> hasn't"]),
    ("how does this change affect the onboarding flow do we need to update the docs to",
     ["How does this change affect the onboarding flow? Do we need to update the docs too?"],
     [P, "to -> too"]),
    ("i'm not sure if your aware but the parking lot will be closed all day tomorrow",
     ["I'm not sure if you're aware, but the parking lot will be closed all day tomorrow."],
     [P, "your -> you're"]),
    ("just landed in denver ill text you when i get to the hotel",
     ["Just landed in Denver. I'll text you when I get to the hotel.",
      "Just landed in Denver! I'll text you when I get to the hotel."],
     [P, "denver -> Denver", "ill -> I'll"]),
    ("the the server went down again last night around three am can someone look into it",
     ["The server went down again last night around 3 a.m. Can someone look into it?",
      "The server went down again last night around three a.m. Can someone look into it?",
      "The server went down again last night around 3 AM. Can someone look into it?"],
     [P, "the the -> The", "am -> a.m./AM"]),
    ("hey mike thanks for covering my shift i owe you one",
     ["Hey Mike, thanks for covering my shift. I owe you one.",
      "Hey Mike, thanks for covering my shift! I owe you one."],
     [P, "mike -> Mike"]),
    ("we past the inspection so we can finally move in on the first",
     ["We passed the inspection, so we can finally move in on the first.",
      "We passed the inspection, so we can finally move in on the first!"],
     [P, "past -> passed"]),
    ("i need you to proofread the proposal before it goes out theres a few typos i couldnt fix",
     ["I need you to proofread the proposal before it goes out. There's a few typos I couldn't fix.",
      "I need you to proofread the proposal before it goes out. There are a few typos I couldn't fix."],
     [P, "theres -> There's", "couldnt -> couldn't"]),
    ("for dinner tonight i was thinking tacos unless you'd rather have pasta let me know",
     ["For dinner tonight, I was thinking tacos, unless you'd rather have pasta. Let me know.",
      "For dinner tonight I was thinking tacos, unless you'd rather have pasta. Let me know!"],
     [P]),
    ("hi dana thanks for sending over the quote it looks good overall but i had a couple questions about the shipping costs their a lot higher then what we paid last year is there any way to bring them down if we commit to a larger order let me know",
     ["Hi Dana, thanks for sending over the quote. It looks good overall, but I had a couple questions about the shipping costs. They're a lot higher than what we paid last year. Is there any way to bring them down if we commit to a larger order? Let me know.",
      "Hi Dana, thanks for sending over the quote. It looks good overall, but I had a couple of questions about the shipping costs - they're a lot higher than what we paid last year. Is there any way to bring them down if we commit to a larger order? Let me know."],
     [P, "dana -> Dana", "their -> They're", "then -> than"]),
    ("can you right down the wifi password for the guests it's on the back of the router",
     ["Can you write down the Wi-Fi password for the guests? It's on the back of the router.",
      "Can you write down the wifi password for the guests? It's on the back of the router.",
      "Can you write down the WiFi password for the guests? It's on the back of the router."],
     [P, "right -> write"]),
    ("i'd rather wait until the data is in then make a decision we'll regret later",
     ["I'd rather wait until the data is in than make a decision we'll regret later."],
     [P, "then -> than"]),
    ("the weather has been terrible all week so the picnic is probably cancelled",
     ["The weather has been terrible all week, so the picnic is probably cancelled.",
      "The weather has been terrible all week, so the picnic is probably canceled."],
     [P]),
    ("witch version of the app are you running the bug might already be fixed",
     ["Which version of the app are you running? The bug might already be fixed."],
     [P, "witch -> Which"]),
    ("i'll send you the address later its a little hard to find so call me if you get lost",
     ["I'll send you the address later. It's a little hard to find, so call me if you get lost."],
     [P, "its -> It's"]),
    ("do you have the the latest version of the budget spreadsheet mine looks out of date",
     ["Do you have the latest version of the budget spreadsheet? Mine looks out of date."],
     [P, "the the -> the"]),
    ("i'm going to be out of the office from the twenty third to the thirtieth please contact jen for anything urgent",
     ["I'm going to be out of the office from the twenty-third to the thirtieth. Please contact Jen for anything urgent.",
      "I'm going to be out of the office from the 23rd to the 30th. Please contact Jen for anything urgent."],
     [P, "twenty third -> twenty-third", "jen -> Jen"]),
    ("great job on the presentation today the client was really impressed",
     ["Great job on the presentation today. The client was really impressed.",
      "Great job on the presentation today! The client was really impressed."],
     [P]),
    ("we could of avoided this whole mess if someone had checked the backups",
     ["We could have avoided this whole mess if someone had checked the backups.",
      "We could've avoided this whole mess if someone had checked the backups."],
     [P, "could of -> could have"]),
    ("did you here that the office is closing early on friday for the holiday",
     ["Did you hear that the office is closing early on Friday for the holiday?"],
     [P, "here -> hear", "friday -> Friday"]),
    ("remind me to renew my passport its expiring in march",
     ["Remind me to renew my passport. It's expiring in March.",
      "Remind me to renew my passport - it's expiring in March."],
     [P, "its -> It's", "march -> March"]),
    ("the package was suppose to arrive yesterday but tracking still says its in transit",
     ["The package was supposed to arrive yesterday, but tracking still says it's in transit.",
      "The package was supposed to arrive yesterday but tracking still says it's in transit."],
     [P, "suppose -> supposed", "its -> it's"]),
    ("so like i was thinking we could split the project into two phases and ship the first one before the holidays",
     ["So, like, I was thinking we could split the project into two phases and ship the first one before the holidays.",
      "So I was thinking we could split the project into two phases and ship the first one before the holidays.",
      "So, I was thinking we could split the project into two phases and ship the first one before the holidays."],
     [P]),
    ("were do you want to have the team offsite this year",
     ["Where do you want to have the team offsite this year?"],
     [P, "were -> Where"]),
    ("sorry i missed your call i was in the shower whats up",
     ["Sorry I missed your call, I was in the shower. What's up?",
      "Sorry, I missed your call. I was in the shower. What's up?",
      "Sorry I missed your call - I was in the shower. What's up?"],
     [P, "whats -> What's"]),
    ("okay so for the trip we need to book the hotel by friday rent a car for the second leg and figure out who's watching the dog i can handle the hotel if you can take care of the car",
     ["Okay, so for the trip we need to book the hotel by Friday, rent a car for the second leg, and figure out who's watching the dog. I can handle the hotel if you can take care of the car.",
      "Okay, so for the trip, we need to book the hotel by Friday, rent a car for the second leg, and figure out who's watching the dog. I can handle the hotel if you can take care of the car."],
     [P, "friday -> Friday"]),
    ("i want to make sure were all on the same page before we present to the board",
     ["I want to make sure we're all on the same page before we present to the board.",
      "I want to make sure we're all on the same page before we present to the Board."],
     [P, "were -> we're"]),
    ("hey can you pick up some milk eggs and bread on your way home",
     ["Hey, can you pick up some milk, eggs, and bread on your way home?",
      "Hey, can you pick up some milk, eggs and bread on your way home?"],
     [P]),
    ("i looked at the analytics and the drop in signups started the same day we changed the pricing page so i doubt its a coincidence can we roll back the change and see if the numbers recover",
     ["I looked at the analytics, and the drop in signups started the same day we changed the pricing page, so I doubt it's a coincidence. Can we roll back the change and see if the numbers recover?",
      "I looked at the analytics and the drop in signups started the same day we changed the pricing page. I doubt it's a coincidence. Can we roll back the change and see if the numbers recover?"],
     [P, "its -> it's"]),
    ("i new this would happen we should have tested it on older devices",
     ["I knew this would happen. We should have tested it on older devices.",
      "I knew this would happen - we should have tested it on older devices."],
     [P, "new -> knew"]),
    ("the price went up by fifteen percent which is more then we budgeted for",
     ["The price went up by fifteen percent, which is more than we budgeted for.",
      "The price went up by 15%, which is more than we budgeted for.",
      "The price went up by 15 percent, which is more than we budgeted for."],
     [P, "then -> than"]),
    ("can we move our one on one to tomorrow morning something came up this afternoon",
     ["Can we move our one-on-one to tomorrow morning? Something came up this afternoon.",
      "Can we move our 1:1 to tomorrow morning? Something came up this afternoon."],
     [P, "one on one -> one-on-one"]),
    ("please make sure you sign the form and bring it with you on monday otherwise they wont let you in",
     ["Please make sure you sign the form and bring it with you on Monday. Otherwise, they won't let you in.",
      "Please make sure you sign the form and bring it with you on Monday; otherwise, they won't let you in.",
      "Please make sure you sign the form and bring it with you on Monday, otherwise they won't let you in."],
     [P, "monday -> Monday", "wont -> won't"]),
    ("i past by your desk earlier but you weren't there so i left the notes on your chair",
     ["I passed by your desk earlier, but you weren't there, so I left the notes on your chair.",
      "I passed by your desk earlier but you weren't there, so I left the notes on your chair.",
      "I went past your desk earlier, but you weren't there, so I left the notes on your chair."],
     [P, "past -> passed"]),
    ("um i think the the deadline is next friday but let me double check with alex",
     ["Um, I think the deadline is next Friday, but let me double-check with Alex.",
      "I think the deadline is next Friday, but let me double-check with Alex.",
      "Um, I think the deadline is next Friday, but let me double check with Alex."],
     [P, "the the -> the", "friday -> Friday", "alex -> Alex"]),
    ("were thinking about adopting a cat do you know any good shelters near here",
     ["We're thinking about adopting a cat. Do you know any good shelters near here?"],
     [P, "were -> We're"]),
    ("so i talked to the vendor this morning and they said the parts wont be ready until next week which means we cant start the install on monday like we planned so i think we should let the client know today rather than wait and maybe offer them a small discount for the delay",
     ["So I talked to the vendor this morning, and they said the parts won't be ready until next week, which means we can't start the install on Monday like we planned. So I think we should let the client know today rather than wait, and maybe offer them a small discount for the delay.",
      "So, I talked to the vendor this morning and they said the parts won't be ready until next week, which means we can't start the install on Monday like we planned. I think we should let the client know today rather than wait, and maybe offer them a small discount for the delay."],
     [P, "wont -> won't", "cant -> can't", "monday -> Monday"]),
    ("hi everyone just a heads up the office will be closed on monday for the holiday if you need access to the building over the long weekend please email facilities by thursday and they'll set you up with a temporary badge thanks and have a great weekend",
     ["Hi everyone, just a heads up: the office will be closed on Monday for the holiday. If you need access to the building over the long weekend, please email facilities by Thursday, and they'll set you up with a temporary badge. Thanks, and have a great weekend!",
      "Hi everyone, just a heads-up: the office will be closed on Monday for the holiday. If you need access to the building over the long weekend, please email Facilities by Thursday and they'll set you up with a temporary badge. Thanks and have a great weekend!",
      "Hi everyone - just a heads up, the office will be closed on Monday for the holiday. If you need access to the building over the long weekend, please email facilities by Thursday, and they'll set you up with a temporary badge. Thanks, and have a great weekend."],
     [P, "monday -> Monday", "thursday -> Thursday"]),
]

CLEAN = [
    "Hey, can you send me the agenda for tomorrow's meeting? I want to add a couple of items.",
    "I'm running about ten minutes late. Go ahead and start without me.",
    "Thanks for jumping on that so quickly. Let me know if you need anything else from me.",
    "Note to self: call the bank about the duplicate charge before Friday.",
    "We're still waiting on the final numbers from finance, so the report will probably slip to next week.",
    "Sounds good to me. I'll book the room and send out the invite this afternoon.",
    "Did you get a chance to look at the draft? No rush, but I'd like to send it to the client by Thursday.",
    "Can you pick up the kids at three? I'm stuck in a meeting that's running over.",
    "Whether we launch on Monday or Tuesday depends on what QA finds, so let's wait for their report before we decide.",
    "The migration took longer than expected, but it's done now and everything looks stable.",
]

out_path = sys.argv[1]
rows = []
for inp, outs, errs in FIX:
    rows.append({"input": inp, "expected": {"kind": "fix", "acceptableOutputs": outs},
                 "errors": errs, "tags": ["dictation"]})
for inp in CLEAN:
    rows.append({"input": inp, "expected": {"kind": "unchanged"}, "errors": [], "tags": ["clean"]})
with open(out_path, "w") as f:
    for i, r in enumerate(rows, 1):
        f.write(json.dumps({"id": f"s3-{i:03d}", **r}, ensure_ascii=False) + "\n")
