import json
import sys

OUT = sys.argv[1]

# (input, [acceptable outputs], [errors], [tags])
FIX = [
    ("Their going to the beach after work if the weather holds.",
     ["They're going to the beach after work if the weather holds.",
      "They are going to the beach after work if the weather holds."],
     ["Their -> They're"], ["grammar", "homophone"]),
    ("I should of called you before I left the office.",
     ["I should have called you before I left the office.",
      "I should've called you before I left the office."],
     ["should of -> should have"], ["grammar", "verb-form"]),
    ("She don't like spicy food.",
     ["She doesn't like spicy food.", "She does not like spicy food."],
     ["don't -> doesn't"], ["grammar", "subject-verb", "short"]),
    ("Me and him went to the hardware store on Saturday.",
     ["He and I went to the hardware store on Saturday."],
     ["Me and him -> He and I"], ["grammar", "pronoun-case"]),
    ("Its been a long week, so lets order pizza tonight.",
     ["It's been a long week, so let's order pizza tonight."],
     ["Its -> It's", "lets -> let's"], ["grammar", "homophone", "apostrophe"]),
    ("I seen the new trailer yesterday and it looks great.",
     ["I saw the new trailer yesterday and it looks great.",
      "I saw the new trailer yesterday, and it looks great."],
     ["seen -> saw"], ["grammar", "verb-form", "casual"]),
    ("We have went over the numbers three times already.",
     ["We have gone over the numbers three times already.",
      "We've gone over the numbers three times already."],
     ["have went -> have gone"], ["grammar", "verb-form"]),
    ("Please submit a application by Friday.",
     ["Please submit an application by Friday."],
     ["a application -> an application"], ["grammar", "article"]),
    ("He is an user of our premium plan.",
     ["He is a user of our premium plan."],
     ["an user -> a user"], ["grammar", "article"]),
    ("The affect of the new policy was immediate.",
     ["The effect of the new policy was immediate."],
     ["affect -> effect"], ["grammar", "homophone"]),
    ("Your going to love the new dashboard.",
     ["You're going to love the new dashboard.",
      "You are going to love the new dashboard."],
     ["Your -> You're"], ["grammar", "homophone"]),
    ("I'm to tired to finish the report tonight.",
     ["I'm too tired to finish the report tonight."],
     ["to tired -> too tired"], ["grammar", "homophone"]),
    ("Make sure you don't loose your boarding pass.",
     ["Make sure you don't lose your boarding pass."],
     ["loose -> lose"], ["grammar", "homophone"]),
    ("The list of items are on the kitchen table.",
     ["The list of items is on the kitchen table."],
     ["are -> is"], ["grammar", "subject-verb"]),
    ("Each of the students have a laptop.",
     ["Each of the students has a laptop."],
     ["have -> has"], ["grammar", "subject-verb"]),
    ("There is three reasons we should postpone the launch.",
     ["There are three reasons we should postpone the launch."],
     ["There is -> There are"], ["grammar", "subject-verb"]),
    ("The dog wagged it's tail when we got home.",
     ["The dog wagged its tail when we got home."],
     ["it's -> its"], ["grammar", "homophone"]),
    ("Between you and I, the meeting could have been an email.",
     ["Between you and me, the meeting could have been an email."],
     ["you and I -> you and me"], ["grammar", "pronoun-case"]),
    ("We did not receive no response from the vendor regarding the overdue invoice.",
     ["We did not receive any response from the vendor regarding the overdue invoice.",
      "We received no response from the vendor regarding the overdue invoice."],
     ["did not receive no -> did not receive any"], ["grammar", "double-negative", "formal"]),
    ("The server went down at noon, we restored it by two.",
     ["The server went down at noon; we restored it by two.",
      "The server went down at noon. We restored it by two.",
      "The server went down at noon, and we restored it by two.",
      "The server went down at noon, but we restored it by two."],
     ["comma splice: noon, we -> noon; we"], ["grammar", "punctuation", "comma-splice"]),
    ("She has wrote three novels since 2015.",
     ["She has written three novels since 2015.",
      "She's written three novels since 2015."],
     ["has wrote -> has written"], ["grammar", "verb-form"]),
    ("If I would have known about the traffic, I would have left earlier.",
     ["If I had known about the traffic, I would have left earlier.",
      "If I'd known about the traffic, I would have left earlier."],
     ["would have known -> had known"], ["grammar", "tense"]),
    ("There were less people at the conference this year.",
     ["There were fewer people at the conference this year."],
     ["less -> fewer"], ["grammar", "comparative"]),
    ("I'm very interested on learning more about the role.",
     ["I'm very interested in learning more about the role."],
     ["interested on -> interested in"], ["grammar", "preposition"]),
    ("We discussed about the budget during the meeting.",
     ["We discussed the budget during the meeting."],
     ["discussed about -> discussed"], ["grammar", "preposition"]),
    ("This is the most easiest recipe I've ever made.",
     ["This is the easiest recipe I've ever made."],
     ["most easiest -> easiest"], ["grammar", "comparative"]),
    ("She bought an new car and a umbrella.",
     ["She bought a new car and an umbrella."],
     ["an new -> a new", "a umbrella -> an umbrella"], ["grammar", "article"]),
    ("They was supposed to arrive at noon, but there flight was delayed.",
     ["They were supposed to arrive at noon, but their flight was delayed."],
     ["was -> were", "there -> their"], ["grammar", "subject-verb", "homophone"]),
    ("Weather or not we finish, we should of told the client.",
     ["Whether or not we finish, we should have told the client.",
      "Whether or not we finish, we should've told the client."],
     ["Weather -> Whether", "should of -> should have"], ["grammar", "homophone", "verb-form"]),
    ("The comittee has postponed the vote untill next week because it's chair is sick.",
     ["The committee has postponed the vote until next week because its chair is sick."],
     ["comittee -> committee", "untill -> until", "it's -> its"], ["grammar", "homophone", "spelling"]),
    ("I recieved you're message and will respond tommorow.",
     ["I received your message and will respond tomorrow."],
     ["recieved -> received", "you're -> your", "tommorow -> tomorrow"], ["grammar", "homophone", "spelling"]),
    ("Their are to many tabs open on my computer.",
     ["There are too many tabs open on my computer."],
     ["Their -> There", "to -> too"], ["grammar", "homophone"]),
    ("The new update effects how notifications are displayed.",
     ["The new update affects how notifications are displayed."],
     ["effects -> affects"], ["grammar", "homophone"]),
    ("We have to accept that are budget is limited this year.",
     ["We have to accept that our budget is limited this year."],
     ["are -> our"], ["grammar", "homophone"]),
    ("I would of gone if I'd known you was coming.",
     ["I would have gone if I'd known you were coming.",
      "I would've gone if I'd known you were coming."],
     ["would of -> would have", "was -> were"], ["grammar", "verb-form", "subject-verb"]),
    ("She don't like it when people is late to meetings.",
     ["She doesn't like it when people are late to meetings.",
      "She does not like it when people are late to meetings."],
     ["don't -> doesn't", "is -> are"], ["grammar", "subject-verb"]),
    ("The results was better then we expected, which is great news for the team.",
     ["The results were better than we expected, which is great news for the team."],
     ["was -> were", "then -> than"], ["grammar", "subject-verb", "homophone"]),
    ("The manager, along with her two assistants, are attending the summit in Toronto.",
     ["The manager, along with her two assistants, is attending the summit in Toronto."],
     ["are -> is"], ["grammar", "subject-verb", "formal"]),
    ("Our quarterly revenue has rose by twelve percent, and we expect further growth in the next fiscal year.",
     ["Our quarterly revenue has risen by twelve percent, and we expect further growth in the next fiscal year."],
     ["has rose -> has risen"], ["grammar", "verb-form", "formal"]),
    ("I'm looking forward to meet you on Thursday.",
     ["I'm looking forward to meeting you on Thursday."],
     ["to meet -> to meeting"], ["grammar", "verb-form"]),
    ("He suggested me to apply for the senior position.",
     ["He suggested that I apply for the senior position.",
      "He suggested I apply for the senior position."],
     ["suggested me to apply -> suggested that I apply"], ["grammar", "verb-form"]),
    ("The contract expires in March, we need to renegotiate the terms before then.",
     ["The contract expires in March; we need to renegotiate the terms before then.",
      "The contract expires in March. We need to renegotiate the terms before then.",
      "The contract expires in March, so we need to renegotiate the terms before then."],
     ["comma splice: March, we -> March; we"], ["grammar", "punctuation", "comma-splice"]),
    ("Where did you put the stapler.",
     ["Where did you put the stapler?"],
     ["stapler. -> stapler?"], ["grammar", "punctuation", "short"]),
    ("However we decided to proceed with the original plan.",
     ["However, we decided to proceed with the original plan."],
     ["However -> However,"], ["grammar", "punctuation"]),
    ("We ordered three pizza's for the team lunch.",
     ["We ordered three pizzas for the team lunch."],
     ["pizza's -> pizzas"], ["grammar", "apostrophe"]),
    ("The principle reason for the delay was a shortage of parts.",
     ["The principal reason for the delay was a shortage of parts."],
     ["principle -> principal"], ["grammar", "homophone", "formal"]),
    ("We past the old library on our way home.",
     ["We passed the old library on our way home."],
     ["past -> passed"], ["grammar", "homophone"]),
    ("He is the person who's car was towed this morning.",
     ["He is the person whose car was towed this morning.",
      "He's the person whose car was towed this morning."],
     ["who's -> whose"], ["grammar", "homophone"]),
    ("lol i think your right about the deadline",
     ["lol i think you're right about the deadline",
      "lol I think you're right about the deadline",
      "lol i think you are right about the deadline"],
     ["your -> you're"], ["grammar", "homophone", "casual", "lowercase"]),
    ("hey, just wanted to say thanks for yesterday. me and Sam had a great time and we should of stayed longer.",
     ["hey, just wanted to say thanks for yesterday. Sam and I had a great time and we should have stayed longer.",
      "hey, just wanted to say thanks for yesterday. Sam and I had a great time and we should've stayed longer.",
      "hey, just wanted to say thanks for yesterday. Sam and I had a great time, and we should have stayed longer."],
     ["me and Sam -> Sam and I", "should of -> should have"],
     ["grammar", "pronoun-case", "verb-form", "casual", "lowercase", "two-sentence"]),
    ("Dear Ms. Patel, I am writing to inform you that you're application have been reviewed and we would like to invite you for a interview next week.",
     ["Dear Ms. Patel, I am writing to inform you that your application has been reviewed and we would like to invite you for an interview next week.",
      "Dear Ms. Patel, I am writing to inform you that your application has been reviewed, and we would like to invite you for an interview next week."],
     ["you're -> your", "have -> has", "a interview -> an interview"],
     ["grammar", "homophone", "subject-verb", "article", "formal", "long"]),
    ("Thank you for you're patience while we resolve the issue, our team is working on it now.",
     ["Thank you for your patience while we resolve the issue. Our team is working on it now.",
      "Thank you for your patience while we resolve the issue; our team is working on it now."],
     ["you're -> your", "comma splice: issue, our -> issue. Our"],
     ["grammar", "homophone", "comma-splice", "formal"]),
    ("The resturant were closed when we arrived, so we went somewhere else.",
     ["The restaurant was closed when we arrived, so we went somewhere else."],
     ["resturant -> restaurant", "were -> was"], ["grammar", "subject-verb", "spelling"]),
    ("I definately think we should of asked for more time.",
     ["I definitely think we should have asked for more time.",
      "I definitely think we should've asked for more time."],
     ["definately -> definitely", "should of -> should have"], ["grammar", "verb-form", "spelling"]),
    ("Alot of people doesn't realize how much water they waste each day.",
     ["A lot of people don't realize how much water they waste each day."],
     ["Alot -> A lot", "doesn't -> don't"], ["grammar", "subject-verb", "spelling"]),
    ("Our neighbors has a beautiful garden in there backyard.",
     ["Our neighbors have a beautiful garden in their backyard."],
     ["has -> have", "there -> their"], ["grammar", "subject-verb", "homophone"]),
    ("This is the worse movie I have ever seen.",
     ["This is the worst movie I have ever seen."],
     ["worse -> worst"], ["grammar", "comparative"]),
    ("Everybody should bring they're own lunch to the workshop.",
     ["Everybody should bring their own lunch to the workshop."],
     ["they're -> their"], ["grammar", "homophone"]),
    ("Its a shame the event was cancelled, it would of been fun.",
     ["It's a shame the event was cancelled; it would have been fun.",
      "It's a shame the event was cancelled. It would have been fun.",
      "It's a shame the event was cancelled; it would've been fun.",
      "It's a shame the event was cancelled. It would've been fun."],
     ["Its -> It's", "comma splice: cancelled, it -> cancelled; it", "would of -> would have"],
     ["grammar", "homophone", "comma-splice", "verb-form"]),
    ("She is a honest person and a excellent manager.",
     ["She is an honest person and an excellent manager.",
      "She's an honest person and an excellent manager."],
     ["a honest -> an honest", "a excellent -> an excellent"], ["grammar", "article"]),
    ("Could you give me an advice on how to structure the report?",
     ["Could you give me some advice on how to structure the report?",
      "Could you give me advice on how to structure the report?"],
     ["an advice -> some advice"], ["grammar", "article"]),
    ("We are waiting for you since nine o'clock.",
     ["We have been waiting for you since nine o'clock.",
      "We've been waiting for you since nine o'clock."],
     ["are waiting -> have been waiting"], ["grammar", "tense"]),
    ("She has finished the report yesterday.",
     ["She finished the report yesterday."],
     ["has finished -> finished"], ["grammar", "tense", "short"]),
    ("The quality of these photos are amazing.",
     ["The quality of these photos is amazing."],
     ["are -> is"], ["grammar", "subject-verb"]),
    ("They have ate all the cookies already.",
     ["They have eaten all the cookies already.",
      "They've eaten all the cookies already."],
     ["have ate -> have eaten"], ["grammar", "verb-form"]),
    ("Me and my team has finished the database migration.",
     ["My team and I have finished the database migration."],
     ["Me and my team -> My team and I", "has -> have"], ["grammar", "pronoun-case", "subject-verb"]),
    ("My brother is more smarter then me at chess.",
     ["My brother is smarter than me at chess.",
      "My brother is smarter than I am at chess."],
     ["more smarter -> smarter", "then -> than"], ["grammar", "comparative", "homophone"]),
    ("The shoes are to loose, so I need a smaller size.",
     ["The shoes are too loose, so I need a smaller size."],
     ["to -> too"], ["grammar", "homophone"]),
    ("Although the shipment were delayed by the storm, the warehouse staff worked threw the weekend and processed every order before the holiday, which our customers appreciated alot.",
     ["Although the shipment was delayed by the storm, the warehouse staff worked through the weekend and processed every order before the holiday, which our customers appreciated a lot."],
     ["were -> was", "threw -> through", "alot -> a lot"],
     ["grammar", "subject-verb", "homophone", "spelling", "long"]),
    ("When you get a chance, could you send me the slides from yesterday's presentation? I want to make sure I didn't miss nothing important before I present to the leadership team on Monday.",
     ["When you get a chance, could you send me the slides from yesterday's presentation? I want to make sure I didn't miss anything important before I present to the leadership team on Monday.",
      "When you get a chance, could you send me the slides from yesterday's presentation? I want to make sure I missed nothing important before I present to the leadership team on Monday."],
     ["didn't miss nothing -> didn't miss anything"],
     ["grammar", "double-negative", "two-sentence", "long"]),
]

CLEAN = [
    "Its battery lasts all day, even with heavy use.",
    "They're over there with their dog.",
    "It's been raining since Tuesday, so the trail is muddy.",
    "Your report was clearer than mine, and you're right about the budget.",
    "The new policy will affect everyone, but its full effect won't be felt until spring.",
    "Whose turn is it to bring snacks? I think it's Sam's.",
    "We had fewer complaints this quarter than we expected.",
    "My sister and I are driving to Montreal, too.",
    "Make sure the lid isn't loose, or you'll lose the soup on the drive.",
    "Between you and me, the new design is much better than the old one.",
]


def with_variants(outputs: list[str]) -> list[str]:
    """Pad to 2-4 variants by toggling the trailing period."""
    result = list(outputs)
    for out in outputs:
        if len(result) >= 4:
            break
        alt = out[:-1] if out.endswith(".") else (out + "." if out[-1].isalpha() else None)
        if alt and alt not in result:
            result.append(alt)
    return result[:4]


with open(OUT, "w") as f:
    n = 0
    for inp, outs, errs, tags in FIX:
        n += 1
        f.write(json.dumps({"id": f"s2-{n:03d}", "input": inp,
                            "expected": {"kind": "fix", "acceptableOutputs": with_variants(outs)},
                            "errors": errs, "tags": tags}) + "\n")
    for inp in CLEAN:
        n += 1
        f.write(json.dumps({"id": f"s2-{n:03d}", "input": inp,
                            "expected": {"kind": "unchanged"}, "errors": [], "tags": ["clean"]}) + "\n")
